name: Create Traing Job on commit
on:
- push
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Create Traing Job in DKube
      run: |
        curl --request POST \
        --url https://18.236.126.102:32222/dkube/v2/users/ocdkube/jobs/ \
        --header "authorization: ${{secrets.JWT_TOKEN}}" \
        --header 'content-type: application/keyauth.api.v1+json' \
        --data "{\"name\":\"commit-${{ github.sha }}\",\"parameters\":{\"class\":\"training\",\"training\":{\"executor\":{\"choice\":\"dkube\",\"dkube\":{\"framework\":{\"choice\":\"tensorflow\",\"details\":{\"tfversion\":\"v1.14\"}}}},\"workspace\":{\"program\":\"ocdkube:mnist\",\"script\":\"python model.py\"},\"models\":[],\"datasets\":[\"ocdkube:mnist\"],\"tags\":[],\"hyperparams\":{\"epochs\":1,\"steps\":100,\"batchsize\":1,\"custom\":[],\"file\":{\"body\":\"\",\"name\":\"\"}},\"nworkers\":0,\"ngpus\":0,\"rdma\":false,\"gpus_override\":false,\"view\":{\"ready\":false}}}}" \
        --insecure 
